// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemGym.Infrastructure.Persistence;

#nullable disable

namespace SystemGym.Infrastructure.Migrations
{
    [DbContext(typeof(SystemGymDbContext))]
    [Migration("20260513180000_MakeSalesHistoryUserIdNullable")]
    partial class MakeSalesHistoryUserIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemGym.Domain.Entities.SalesHistory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ClientId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("FechaVenta")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("MedioPago")
                    .HasColumnType("text");

                b.Property<decimal>("Monto")
                    .HasColumnType("numeric(18,2)");

                b.Property<bool>("Pagado")
                    .HasColumnType("boolean");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<string>("Referencia")
                    .HasColumnType("text");

                b.Property<Guid?>("SubscriptionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex(new[] { "ClientId", "FechaVenta" });

                b.HasIndex(new[] { "FechaVenta" });

                b.ToTable("SalesHistories");
            });

#pragma warning restore 612, 618
        }
    }
}
